### ISSUE TITLE
SSL Redirection Forbidden 

### ISSUE THREAD

**Issue by Tearstone** [rverton/DrupalScan#1]
Ran this against a known Drupal 7 site to determine it's precise version, I get this in return. I tried this on drupal.com and received the same issue. 

/usr/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://drupal.org/project/contrib -> https://www.drupal.org/project/contrib (RuntimeError)
    from /usr/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /usr/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /var/lib/gems/1.9.1/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:34:in `block in enumerateModules'
    from /var/lib/gems/1.9.1/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:28:in`each'
    from /var/lib/gems/1.9.1/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:28:in `enumerateModules'
    from /var/lib/gems/1.9.1/gems/DrupalScan-0.5.2/bin/DrupalScan:33:in`<top (required)>'
    from /usr/local/bin/DrupalScan:23:in `load'
    from /usr/local/bin/DrupalScan:23:in`<main>'

**Comment by darryllane** [comment]
Im getting he same issue, is this not maintained anymore?

/usr/lib/ruby/2.1.0/open-uri.rb:223:in `open_loop': redirection forbidden: http://drupal.org/project/content -> https://drupal.org/project/content (RuntimeError)
    from /usr/lib/ruby/2.1.0/open-uri.rb:149:in`open_uri'
    from /usr/lib/ruby/2.1.0/open-uri.rb:704:in `open'
    from /usr/lib/ruby/2.1.0/open-uri.rb:34:in`open'
    from /var/lib/gems/2.1.0/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:34:in `block in enumerateModules'
    from /var/lib/gems/2.1.0/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:28:in`each'
    from /var/lib/gems/2.1.0/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:28:in `enumerateModules'
    from /var/lib/gems/2.1.0/gems/DrupalScan-0.5.2/bin/DrupalScan:33:in`<top (required)>'
    from /usr/local/bin/DrupalScan:23:in `load'
    from /usr/local/bin/DrupalScan:23:in`<main>'
root@kali-sec:~#

**Comment by rverton** [comment]
Hi,
sorry this project is not maintained anymore. Please use a more up to date software like https://github.com/droope/droopescan

Bests,
robin
